sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - stable
  - 4
before_script:  
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Check the size of caches
  - du -sh ./node_modules ./bower_components/ ./docs/bower_components/ || true
  # Install npm dependencies and ensure that npm cache is not stale
  - npm install
script:
  - karma start --single-run